apiVersion: v1
kind: Pod
metadata:
  name: t2t
spec:
  containers:
    - args:
      - t2t-trainer
      - --data_dir=/tensor2tensor/t2t_data
      - --problem=translate_ende_wmt32k
      - --model=transformer
      - --hparams_set=transformer_base_single_gpu
      - --output_dir=/root/t2t_train/translate_ende_wmt32k/transformer-transformer_base_single_gpu
      - --log_level=30
      - --benchmark_steps=30
      name: t2t-container
      image: piotrowskidariusz/tensor2tensor:old
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
      resources:
        limits:
          nvidia.com/gpu: 1
  restartPolicy: Never   
